--Q7: V
	SELECT j.TIME1, t.ESTADO AS ESTADO_T1, j.TIME2, t2.ESTADO AS ESTADO_T2, j.CLASSICO 
		FROM JOGA j 
			JOIN "TIME" t ON t.NOME  = j.TIME1
			JOIN "TIME" t2 ON t2.NOME = j.TIME2 
				WHERE j.CLASSICO = 'S';
